import Box from "@mui/material/Box";
import Chip from "@mui/material/Chip";
import Divider from "@mui/material/Divider";
import Stack from "@mui/material/Stack";
import Table from "@mui/material/Table";
import TableBody from "@mui/material/TableBody";
import TableCell from "@mui/material/TableCell";
import TableHead from "@mui/material/TableHead";
import TableRow from "@mui/material/TableRow";
import Typography from "@mui/material/Typography";
import { notFound, redirect } from "next/navigation";
import { PrintButton } from "@/components/print-button";
import { getSession } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { projectInActiveWorkspace } from "@/lib/workspace";

export const dynamic = "force-dynamic";

export default async function PlanReportPage(
  props: PageProps<"/report/plan/[planId]">,
) {
  if (!(await getSession())) redirect("/login");

  const { planId } = await props.params;
  const plan = await prisma.testPlan.findUnique({
    where: { id: planId },
    include: {
      project: { select: { id: true, key: true, name: true } },
      runs: {
        orderBy: { createdAt: "desc" },
        include: {
          executions: { select: { status: true } },
          _count: { select: { items: true, executions: true } },
        },
      },
    },
  });
  if (!plan) notFound();
  if (!(await projectInActiveWorkspace(plan.project.id))) notFound();

  const runStats = plan.runs.map((run) => {
    const passed = run.executions.filter((e) => e.status === "PASS").length;
    const failed = run.executions.filter((e) => e.status === "FAIL").length;
    const executed = run.executions.length;
    const total = run._count.items;
    return {
      id: run.id,
      name: run.name,
      status: run.status,
      total,
      executed,
      passed,
      failed,
      passRate: executed > 0 ? Math.round((passed / executed) * 100) : 0,
    };
  });

  const totalExecuted = runStats.reduce((sum, run) => sum + run.executed, 0);
  const totalPassed = runStats.reduce((sum, run) => sum + run.passed, 0);
  const totalFailed = runStats.reduce((sum, run) => sum + run.failed, 0);
  const overallPassRate =
    totalExecuted > 0 ? Math.round((totalPassed / totalExecuted) * 100) : 0;

  return (
    <Box
      sx={{
        maxWidth: 960,
        mx: "auto",
        p: 4,
        bgcolor: "background.paper",
        color: "text.primary",
      }}
    >
      <Stack
        direction="row"
        sx={{ justifyContent: "space-between", alignItems: "flex-start", mb: 2 }}
      >
        <Box>
          <Typography variant="overline" color="text.secondary">
            TestHub · Test plan report
          </Typography>
          <Typography variant="h4" sx={{ fontWeight: 700 }}>
            {plan.name}
          </Typography>
          <Typography color="text.secondary">
            {plan.project.name} ({plan.project.key})
          </Typography>
        </Box>
        <PrintButton />
      </Stack>

      <Chip size="small" label={plan.status} sx={{ mb: 2 }} />

      <Typography variant="subtitle1" sx={{ fontWeight: 600, mb: 2 }}>
        Overall: {overallPassRate}% pass rate · {totalPassed} passed ·{" "}
        {totalFailed} failed · {totalExecuted} executed across {runStats.length} run(s)
      </Typography>

      <Divider sx={{ my: 2 }} />

      <Table size="small">
        <TableHead>
          <TableRow>
            <TableCell>Run</TableCell>
            <TableCell>Status</TableCell>
            <TableCell align="right">Executed</TableCell>
            <TableCell align="right">Passed</TableCell>
            <TableCell align="right">Failed</TableCell>
            <TableCell align="right">Pass rate</TableCell>
          </TableRow>
        </TableHead>
        <TableBody>
          {runStats.map((run) => (
            <TableRow key={run.id} sx={{ pageBreakInside: "avoid" }}>
              <TableCell>{run.name}</TableCell>
              <TableCell>{run.status}</TableCell>
              <TableCell align="right">
                {run.executed}/{run.total}
              </TableCell>
              <TableCell align="right">{run.passed}</TableCell>
              <TableCell align="right">{run.failed}</TableCell>
              <TableCell align="right">{run.passRate}%</TableCell>
            </TableRow>
          ))}
        </TableBody>
      </Table>

      <Divider sx={{ my: 3 }} />
      <Typography variant="caption" color="text.secondary">
        Generated by TestHub · {new Date().toLocaleString()}
      </Typography>
    </Box>
  );
}
